-- MySQL Script generated by MySQL Workbench
-- Mon Dec 22 19:06:02 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Habitat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Habitat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Habitat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Habitat` ;

-- -----------------------------------------------------
-- Table `Habitat`.`Actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Actividades` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Actividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`FichasPessoais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`FichasPessoais` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`FichasPessoais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataNascimento` DATE NULL,
  `CartaoCidadao` VARCHAR(10) NULL,
  `Contribuinte` VARCHAR(10) NULL,
  `NumSegSocial` VARCHAR(10) NULL,
  `Pais` VARCHAR(30) NULL,
  `Localidade` VARCHAR(30) NULL,
  `Rua` VARCHAR(100) NULL,
  `CodigoPostal` VARCHAR(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Funcionarios` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Ficha` INT NOT NULL,
  `Salario` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Funcionarios_FichasPessoais1_idx` (`Ficha` ASC),
  CONSTRAINT `fk_Funcionarios_FichasPessoais1`
    FOREIGN KEY (`Ficha`)
    REFERENCES `Habitat`.`FichasPessoais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Paises` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Paises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Equipas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Equipas` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Equipas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Responsavel` INT NULL,
  `Pais` INT NULL,
  `Designacao` VARCHAR(75) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Grupos_Funcionarios1_idx` (`Responsavel` ASC),
  INDEX `fk_Equipas_Pais1_idx` (`Pais` ASC),
  CONSTRAINT `fk_Grupos_Funcionarios1`
    FOREIGN KEY (`Responsavel`)
    REFERENCES `Habitat`.`Funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipas_Pais1`
    FOREIGN KEY (`Pais`)
    REFERENCES `Habitat`.`Paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Voluntarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Voluntarios` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Voluntarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Actividade` INT NOT NULL,
  `Equipa` INT NOT NULL,
  `Nacionalidade` INT NOT NULL,
  `Ficha` INT NOT NULL,
  `FichaInscricao` VARCHAR(45) NULL,
  `HorasTrabalho` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Voluntarios_Profissao_idx` (`Actividade` ASC),
  INDEX `fk_Voluntarios_Grupos1_idx` (`Equipa` ASC),
  INDEX `fk_Voluntarios_FichasPessoais1_idx` (`Ficha` ASC),
  INDEX `fk_Voluntarios_Pais1_idx` (`Nacionalidade` ASC),
  CONSTRAINT `fk_Voluntarios_Profissao`
    FOREIGN KEY (`Actividade`)
    REFERENCES `Habitat`.`Actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voluntarios_Grupos1`
    FOREIGN KEY (`Equipa`)
    REFERENCES `Habitat`.`Equipas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voluntarios_FichasPessoais1`
    FOREIGN KEY (`Ficha`)
    REFERENCES `Habitat`.`FichasPessoais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voluntarios_Pais1`
    FOREIGN KEY (`Nacionalidade`)
    REFERENCES `Habitat`.`Paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`TiposDador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`TiposDador` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`TiposDador` (
  `Sigla` VARCHAR(4) NOT NULL,
  `Descricao` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`Sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Dadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Dadores` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Dadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(4) NOT NULL,
  `Ficha` INT NOT NULL,
  `UltimaDoacao` DATETIME NULL,
  `Descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Dadores_FichasPessoais1_idx` (`Ficha` ASC),
  INDEX `fk_Dadores_TiposDador1_idx` (`Tipo` ASC),
  CONSTRAINT `fk_Dadores_FichasPessoais1`
    FOREIGN KEY (`Ficha`)
    REFERENCES `Habitat`.`FichasPessoais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dadores_TiposDador1`
    FOREIGN KEY (`Tipo`)
    REFERENCES `Habitat`.`TiposDador` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`TiposDoacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`TiposDoacao` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`TiposDoacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(75) NOT NULL,
  `Quantidade` FLOAT NOT NULL,
  `Unidades` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Doacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Doacoes` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Doacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` INT NOT NULL,
  `Dador` INT NOT NULL,
  `Funcionario` INT NULL,
  `Quantidade` FLOAT NOT NULL,
  `Gasto` FLOAT NULL,
  `Data` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Doacoes_Dadores1_idx` (`Dador` ASC),
  INDEX `fk_Doacoes_TiposDoacao1_idx` (`Tipo` ASC),
  INDEX `fk_Doacoes_Funcionarios1_idx` (`Funcionario` ASC),
  CONSTRAINT `fk_Doacoes_Dadores1`
    FOREIGN KEY (`Dador`)
    REFERENCES `Habitat`.`Dadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doacoes_TiposDoacao1`
    FOREIGN KEY (`Tipo`)
    REFERENCES `Habitat`.`TiposDoacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doacoes_Funcionarios1`
    FOREIGN KEY (`Funcionario`)
    REFERENCES `Habitat`.`Funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`TiposTarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`TiposTarefa` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`TiposTarefa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Familias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Familias` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Familias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Representante` INT NOT NULL,
  `RendimentoTotal` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Familias_FichasPessoais1_idx` (`Representante` ASC),
  CONSTRAINT `fk_Familias_FichasPessoais1`
    FOREIGN KEY (`Representante`)
    REFERENCES `Habitat`.`FichasPessoais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Candidaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Candidaturas` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Candidaturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(20) NOT NULL,
  `Familia` INT NOT NULL,
  `FichaInscricao` VARCHAR(50) NOT NULL,
  `DataRegisto` DATE NOT NULL,
  `Funcionario` INT NULL,
  `Arquivo` VARCHAR(50) NULL,
  `Descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Candidaturas_Familias1_idx` (`Familia` ASC),
  INDEX `fk_Candidaturas_Funcionarios1_idx` (`Funcionario` ASC),
  CONSTRAINT `fk_Candidaturas_Familias1`
    FOREIGN KEY (`Familia`)
    REFERENCES `Habitat`.`Familias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidaturas_Funcionarios1`
    FOREIGN KEY (`Funcionario`)
    REFERENCES `Habitat`.`Funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Projectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Projectos` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Projectos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Candidatura` INT NOT NULL,
  `Inicio` DATE NOT NULL,
  `ConcluidoA` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Projetos_Candidaturas1_idx` (`Candidatura` ASC),
  CONSTRAINT `fk_Projetos_Candidaturas1`
    FOREIGN KEY (`Candidatura`)
    REFERENCES `Habitat`.`Candidaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Tarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Tarefas` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Tarefas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` INT NOT NULL,
  `Projecto` INT NOT NULL,
  `Inicio` DATE NULL,
  `Fim` DATE NULL,
  INDEX `fk_DoacoesTarefas_Tarefas1_idx` (`Tipo` ASC),
  INDEX `fk_DoacoesTarefas_Projeto1_idx` (`Projecto` ASC),
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_DoacoesTarefas_Tarefas1`
    FOREIGN KEY (`Tipo`)
    REFERENCES `Habitat`.`TiposTarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DoacoesTarefas_Projeto1`
    FOREIGN KEY (`Projecto`)
    REFERENCES `Habitat`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`VoluntariosTarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`VoluntariosTarefas` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`VoluntariosTarefas` (
  `Voluntario` INT NOT NULL,
  `Tarefa` INT NOT NULL,
  `Horas` FLOAT NOT NULL,
  INDEX `fk_TarefasVoluntarios_Voluntarios1_idx` (`Voluntario` ASC),
  PRIMARY KEY (`Voluntario`, `Tarefa`),
  INDEX `fk_VoluntariosTarefas_Tarefas1_idx` (`Tarefa` ASC),
  CONSTRAINT `fk_TarefasVoluntarios_Voluntarios1`
    FOREIGN KEY (`Voluntario`)
    REFERENCES `Habitat`.`Voluntarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VoluntariosTarefas_Tarefas1`
    FOREIGN KEY (`Tarefa`)
    REFERENCES `Habitat`.`Tarefas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`AgregadoFamiliar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`AgregadoFamiliar` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`AgregadoFamiliar` (
  `Ficha` INT NOT NULL,
  `Familia` INT NOT NULL,
  `Rendimento` FLOAT NOT NULL,
  `Habilitacoes` VARCHAR(45) NULL,
  INDEX `fk_Pessoas_Familias1_idx` (`Familia` ASC),
  INDEX `fk_AgregadoFamiliar_FichasPessoais1_idx` (`Ficha` ASC),
  PRIMARY KEY (`Ficha`, `Familia`),
  CONSTRAINT `fk_Pessoas_Familias1`
    FOREIGN KEY (`Familia`)
    REFERENCES `Habitat`.`Familias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgregadoFamiliar_FichasPessoais1`
    FOREIGN KEY (`Ficha`)
    REFERENCES `Habitat`.`FichasPessoais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`Contactos` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`Contactos` (
  `Ficha` INT NOT NULL,
  `Concacto` INT NOT NULL,
  PRIMARY KEY (`Ficha`, `Concacto`),
  INDEX `fk_Contactos_Moradas&Contactos1_idx` (`Ficha` ASC),
  CONSTRAINT `fk_Contactos_Moradas&Contactos1`
    FOREIGN KEY (`Ficha`)
    REFERENCES `Habitat`.`FichasPessoais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`DoacoesProjectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitat`.`DoacoesProjectos` ;

CREATE TABLE IF NOT EXISTS `Habitat`.`DoacoesProjectos` (
  `Doacao` INT NOT NULL,
  `Projecto` INT NOT NULL,
  `Quantidade` FLOAT NOT NULL,
  INDEX `fk_DoacoesProjetos_DoacoesProjetos1_idx` (`Doacao` ASC),
  INDEX `fk_DoacoesProjetos_Projetos1_idx` (`Projecto` ASC),
  PRIMARY KEY (`Doacao`, `Projecto`),
  CONSTRAINT `fk_DoacoesProjetos_DoacoesProjetos1`
    FOREIGN KEY (`Doacao`)
    REFERENCES `Habitat`.`Doacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DoacoesProjetos_Projetos1`
    FOREIGN KEY (`Projecto`)
    REFERENCES `Habitat`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
